server:
  port: 8080
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8

spring:
  application:
    name: swagger2word
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5


# Swagger json url address
# etc. https://petstore.swagger.io/
#swagger.url: http://localhost:8081/v2/api-docs
swagger.url: http://192.168.3.237:8886/v2/api-docs






